config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'
  get 'about', to: 'pages#about' 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :articles, :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user

    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}

end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase}
    has_many :articles, dependent: :destroy

    VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
    validates :email, presence: true, uniqueness: {case_sensitive: false}, format: { with: VALID_EMAIL_REGEX }, length: {maximum: 105}

    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in
        !!current_user
    end

    def require_user
        if !logged_in
            flash[:alert] = "You must be logged in"
            redirect_to login_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController <  ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
    end

    def index
      @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
      @article = Article.new
    end

 
    def edit
    end

    def create
      @article = Article.new(article_params)
      @article.user = current_user
      if @article.save
        flash[:notice] = "Article has been created successfully"
        redirect_to @article
      else
        render :new, status: 422      
      end
    end

    def update
      if @article.update(article_params)
        flash[:notice] = "Article has been edited successfully"
        redirect_to @article
      else
        render :edit, status: 422      
      end
    end

    def destroy
      @article.destroy
      redirect_to articles_path
    end

    private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own article"
        redirect_to @article
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
        redirect_to articles_path if logged_in
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController <  ApplicationController

def new
end

def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = "You have logged in successfully"
        redirect_to user
    else
        flash.now[:alert] = "There was an issue with your login credentials"
        render :new, status: 422   
    end
end

def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController <  ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:show, :index, :new, :create]
    before_action :require_same_user, only: [:edit, :update, :destroy]
  
    def show
        @articles = @user.articles
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def new
    @user = User.new
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Your profile has been edited successfully"
            redirect_to @user
          else
            render :edit, status: 422      
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome #{@user.username}, your account has been created successfully"
            redirect_to articles_path
          else
            render :new, status: 422      
          end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and articles have been deleted"
        redirect_to root_path
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
  
    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
          flash[:alert] = "You can only edit or delete your own profile"
          redirect_to root_path
        end
      end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = {size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(image_src, alt: user.username, class: 'rounded shadow mx-auto d-block mb-4')
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |a| %>
    <div class="card text-center col-8 mb-4 mx-auto shadow">
        <div class="card-header">
            by - <%= link_to a.user.username, user_path(a.user) %>
        </div>
        <div class="card-body">
            <h5 class="card-title"><%= a.title %></h5>
            <p class="card-text"><%= a.description %></p>
            <%= link_to 'Show', article_path(a.id), class: 'btn btn-outline-success' %>
            <% if logged_in && (current_user == a.user || current_user.admin?) %>
                <%= link_to 'Edit', edit_article_path(a.id), class: 'btn btn-outline-info' %>
                <%= link_to 'Delete', article_path(a.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %>
            <% end %>
        </div>
        <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(a.created_at) %> ago,
            edited <%= time_ago_in_words(a.updated_at) %> ago</small>
        </div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<div class="container">
    <%= render 'shared/errors', obj:@article %>
    <div class="row justify-content-center bg-info p-4 rounded mt-4">
            <%= form_with(model: @article, local: true) do |f| %>
                <div class="row mb-3">
                    <div class="col-2">
                        <%= f.label :title, class: "col-form-label" %><br/>
                    </div>
                    <div class="col-10">
                        <%= f.text_field :title, class: "form-control" %>
                    </div>    
                </div>
                <div class="row mb-4">
                    <div class="col-2">
                        <%= f.label :description, class: "col-form-label" %><br/>
                    </div>    
                    <div class="col-10">
                        <%= f.text_area :description, class: "form-control" %>
                    </div>    
                </div>
                <div class="mb-3 d-flex justify-content-center">
                    <%= f.submit class: "btn btn-primary" %>
                </div>

            <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<div class="container">
    <h1 class='text-center'>Edit this article</h1>

    <div class="col-8 mx-auto bg-info p-4 rounded">
        <%= render 'form' %>
    </div>
</div>

app/views/articles/index.html.erb
<h1 class='text-center py-4'>Articles listing Page!</h1>

<div class="digg_pagination mb-4 align-self-center">
    <%= will_paginate @articles, class: 'text-center mb-4' %>
</div>

<%= render 'article', @user %>

<div class="digg_pagination align-self-center">
    <%= will_paginate @articles, class: 'text-center mb-4' %>
</div>

app/views/articles/new.html.erb
<div class='container'>
<h1 class='text-center'>Create a new article</h1>
    

    <div class="col-8 mx-auto">
        <%= render 'form' %>
    </div>
</div>

app/views/articles/show.html.erb
<div class="container">
    <h1 class='text-center'><%=  @article.title %></h1>

    <div class="card text-center col-8 mb-4 mx-auto shadow">
        <div class="card-header">
        By - <%= link_to @article.user.username, user_path(@article.user) %>
        </div>
        <div class="card-body">
            <div class="card-text text-start"><%= simple_format(@article.description) %></div>
            <% if logged_in && (current_user == @article.user || current_user.admin?) %>
                <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-outline-success' %>
                <%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %>
            <% end %>
        </div>
        <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom border-top bg-light py-4 justify-items-center">
    <div class='container'>
        <p class="text-center text-muted">© 2022 Company, Inc</p>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
        <div class="alert alert-success" role="alert">
        <%= msg %>
        </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <%= link_to "Ruby Playground", root_path, class: 'navbar-brand'%>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Bloggers", users_path, class: 'nav-link'%>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Articles
              </a>
              <ul class="dropdown-menu">
                <% if logged_in %>
                  <li><%= link_to "Create new article", new_article_path, class: 'dropdown-item'%></li>
                <%  end  %>
                <li><%= link_to "View articles", articles_path, class: 'dropdown-item'%></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "About", about_path, class: 'dropdown-item'%></li>
              </ul>
            </li>
            <% if logged_in %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Profile <%= "(Admin)" if current_user.admin? %>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "View Profile", user_path(current_user), class: 'dropdown-item'%></li>
                  <li><%= link_to "Edit your profile", edit_user_path(current_user), class: 'dropdown-item'%></li>
                </ul>
              </li>
            <%  end  %>
           <% if logged_in %>
              <li class="nav-item">
                <%= link_to "Log out", logout_path, data: { turbo_method: :delete }, class: 'nav-link' %>
              </li>
            <%  else  %>
              <li class="nav-item">
                <%= link_to "Log in", login_path, class: 'nav-link'%>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_path, class: 'nav-link'%>
              </li>
            <%  end  %>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyPlayground</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='d-flex flex-column'>
      
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<button><%= link_to 'Articles List', articles_path %></button>
<button><%= link_to 'Home', root_path %></button>

app/views/pages/home.html.erb
<div class='container home-container  d-flex flex-column h-100'>
    <div class='d-flex justify-content-center p-5 rounded-3 home-jumbo text-center align-items-center'>
        <div>
            <p class='jumbo-header'>Ruby Playground!</p>
            <p class='jumbo-subtext'>This is a simple hero unit, a simple Jumbotron-style component for calling extra attention to fearured content or infomration.</p>
            <%= link_to "Sign up", new_user_path, class: "btn btn-success btn-lg" %>
        </div>
    </div>
 </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row justify-content-center alert alert-danger alert-dismissible fade show">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <h2>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h2>
    <ul>
    <% obj.errors.full_messages.each do |err| %>
    <li> <%= err %> </li>
        <% end %>
    </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <%= render 'shared/errors', obj:@user %>
    <div class="row justify-content-center bg-info p-4 rounded mt-4">
            <%= form_with(model: @user, local: true) do |f| %>
                <div class="row mb-3">
                    <div class="col-1">
                        <%= f.label :username, class: "col-form-label" %><br/>
                    </div>
                    <div class="col-11">
                        <%= f.text_field :username, class: "form-control", placeholder: 'Enter a username' %>
                    </div>    
                </div>
                <div class="row mb-4">
                    <div class="col-1">
                        <%= f.label :email, class: "col-form-label" %><br/>
                    </div>    
                    <div class="col-11">
                        <%= f.email_field :email, class: "form-control", placeholder: 'Enter your email' %>
                    </div>    
                </div>
                <div class="row mb-4">
                    <div class="col-1">
                        <%= f.label :password, class: "col-form-label" %><br/>
                    </div>    
                    <div class="col-11">
                        <%= f.password_field :password, class: "form-control", placeholder: 'Enter a password' %>
                    </div>    
                </div>
                <div class="mb-3 d-flex justify-content-center">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light") %>
                </div>

            <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container">
    <h1 class='text-center mt-4'>Edit your user information</h1>

    <div class="col-10 mx-auto bg-info p-4 rounded">
        <%= render 'form' %>
    </div>
</div>

app/views/users/index.html.erb
    <h1 class='text-center my-4'>Meet the bloggers</h1>

    <div class="digg_pagination mb-4 align-self-center">
        <%= will_paginate @users, class: 'text-center mb-4' %>
    </div>


    <% @users.each do |user| %>
        <div class="card text-center col-8 mb-4 mx-auto shadow">
            <div class="card-header">
                by - <%= link_to user.username, user_path(user.id) %>
            </div>
            <div class="card-body">
                <%= gravatar_for user, size: 150 %>
                <p classs='card-text'> <%= pluralize(user.articles.count, "article") %></p>
                <%= link_to 'View profile', user_path(user.id), class: 'btn btn-outline-success' %>
                <% if logged_in && current_user == user %>
                    <%= link_to 'Edit', edit_user_path(user.id), class: 'btn btn-outline-info' %>
                <% end %>
                <% if current_user.admin? %>
                    <%= link_to 'Delete user', user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %>
                <% end %>

            </div>
            <div class="card-footer text-muted">
                <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
            </div>
        </div>
    <% end %>

    <div class="digg_pagination mb-4 align-self-center">
        <%= will_paginate @users, class: 'text-center mb-4' %>
    </div>

app/views/users/new.html.erb
<h1 class='text-center mt-4'>Sign up!</h1>

<%= render 'form' %>

app/views/users/show.html.erb
    <h1 class='text-center my-4'><%=  @user.username %>'s Profile</h1>

    <%= gravatar_for @user, size: 200 %>

    <% if current_user == @user %>
        <div class="mx-auto">
            <%= link_to 'Edit your profile', edit_user_path(@user), class: 'btn btn-outline-info mb-4' %>
            <%= link_to 'Delete your profile', user_path(current_user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-outline-danger mb-4' %>
        </div>
    <% end %>
    <% if @articles.length > 0 %>
            <%= render 'articles/article' %>
        <% else %>
            <h1 class='mx-auto mb-4'>No articles to display</h1>
            <% if current_user == @user %>
                <%= link_to 'Write first article', new_article_path, class: 'btn btn-success mb-4 mx-auto' %>
            <% end %>
    <% end %>